name: CI

on:

  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: list directory
        run: ls -l /home/runner/work/ins_acctai/ && pwd
      - name: rsync over ssh
        run: rsync -avz --progress -e "ssh -p18765" ./ins_acctai/test.html u5-u4xjfgg4m0ow@c96105.sgvps.net:www/builder/
